version: '3.7'

services:
  homepage_service:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./homepage-service/:/app/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URI=postgresql://Hichem:Hich@homepage_db/homepage_db_dev
    depends_on:
      - homepage_db
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

  homepage_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data_homepage:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=Hichem
      - POSTGRES_PASSWORD=Hich
      - POSTGRES_DB=homepage_db_dev

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - homepage_service

volumes:
  postgres_data_homepage: